// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import * as Igor from './igor';
import * as CommonProtocol from './common-protocol';

export enum AccessRole {
    /** Maintainer */
    Maintainer = 1,
    /** Administrator */
    Admin = 2
}

export namespace AccessRole {
    export function toJson(value: AccessRole): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): AccessRole {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: AccessRole): Igor.Json.JsonValue {
        switch (value) {
            case AccessRole.Maintainer:
                return 'maintainer';
            case AccessRole.Admin:
                return 'admin';
            default:
                throw new Error(`Invalid AccessRole value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): AccessRole {
        switch (json) {
            case 'maintainer':
                return AccessRole.Maintainer;
            case 'admin':
                return AccessRole.Admin;
            default:
                throw new Error(`Invalid AccessRole value: ${json}`);
        }
    }

    export function getDescription(value: AccessRole): string {
        switch (value) {
            case AccessRole.Maintainer:
                return 'Maintainer';
            case AccessRole.Admin:
                return 'Administrator';
            default:
                return '';
        }
    }
}

export class AccessRoleObject {
    role?: AccessRole | null = null;

    static fromJson(json: Igor.Json.JsonValue): AccessRoleObject {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new AccessRoleObject();
        obj.role =
            'role' in jsonObject && jsonObject['role'] != null
                ? AccessRole.fromJson(jsonObject['role'])
                : null;
        return obj;
    }

    static toJson(value: AccessRoleObject): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        if (value.role != null) result['role'] = AccessRole.toJson(value.role);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return AccessRoleObject.toJson(this);
    }
}

export class PersonnelAccount {
    id!: number;
    rev!: number;
    username!: string;
    name?: string | null = null;
    email?: string | null = null;
    phone?: string | null = null;
    officeId?: number | null = null;
    officeName?: string | null = null;
    officeCountryAlpha2?: string | null = null;
    officeCountryName?: string | null = null;
    department?: string | null = null;
    jobTitle?: string | null = null;
    isBlocked!: boolean;
    isDeleted!: boolean;
    isSuperadmin!: boolean;
    isOfficeManager!: boolean;
    supervisorId?: number | null = null;
    location?: string | null = null;
    supervisorUsername?: string | null = null;
    supervisorName?: string | null = null;
    allocatedToProjectId?: number | null = null;
    allocatedToProjectName?: string | null = null;
    linkedToProjects!: Igor.Json.JsonValue;
    roleId?: number | null = null;
    roleCode?: string | null = null;
    roleTitle?: string | null = null;
    highlights!: Igor.Json.JsonValue;
    hiredAt?: Date | null = null;
    firedAt?: Date | null = null;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): PersonnelAccount {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelAccount();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.username = jsonObject['username'] as string;
        obj.name =
            'name' in jsonObject && jsonObject['name'] != null
                ? (jsonObject['name'] as string)
                : null;
        obj.email =
            'email' in jsonObject && jsonObject['email'] != null
                ? (jsonObject['email'] as string)
                : null;
        obj.phone =
            'phone' in jsonObject && jsonObject['phone'] != null
                ? (jsonObject['phone'] as string)
                : null;
        obj.officeId =
            'office_id' in jsonObject && jsonObject['office_id'] != null
                ? (jsonObject['office_id'] as number)
                : null;
        obj.officeName =
            'office_name' in jsonObject && jsonObject['office_name'] != null
                ? (jsonObject['office_name'] as string)
                : null;
        obj.officeCountryAlpha2 =
            'office_country_alpha2' in jsonObject && jsonObject['office_country_alpha2'] != null
                ? (jsonObject['office_country_alpha2'] as string)
                : null;
        obj.officeCountryName =
            'office_country_name' in jsonObject && jsonObject['office_country_name'] != null
                ? (jsonObject['office_country_name'] as string)
                : null;
        obj.department =
            'department' in jsonObject && jsonObject['department'] != null
                ? (jsonObject['department'] as string)
                : null;
        obj.jobTitle =
            'job_title' in jsonObject && jsonObject['job_title'] != null
                ? (jsonObject['job_title'] as string)
                : null;
        obj.isBlocked = jsonObject['is_blocked'] as boolean;
        obj.isDeleted = jsonObject['is_deleted'] as boolean;
        obj.isSuperadmin = jsonObject['is_superadmin'] as boolean;
        obj.isOfficeManager = jsonObject['is_office_manager'] as boolean;
        obj.supervisorId =
            'supervisor_id' in jsonObject && jsonObject['supervisor_id'] != null
                ? (jsonObject['supervisor_id'] as number)
                : null;
        obj.location =
            'location' in jsonObject && jsonObject['location'] != null
                ? (jsonObject['location'] as string)
                : null;
        obj.supervisorUsername =
            'supervisor_username' in jsonObject && jsonObject['supervisor_username'] != null
                ? (jsonObject['supervisor_username'] as string)
                : null;
        obj.supervisorName =
            'supervisor_name' in jsonObject && jsonObject['supervisor_name'] != null
                ? (jsonObject['supervisor_name'] as string)
                : null;
        obj.allocatedToProjectId =
            'allocated_to_project_id' in jsonObject && jsonObject['allocated_to_project_id'] != null
                ? (jsonObject['allocated_to_project_id'] as number)
                : null;
        obj.allocatedToProjectName =
            'allocated_to_project_name' in jsonObject &&
            jsonObject['allocated_to_project_name'] != null
                ? (jsonObject['allocated_to_project_name'] as string)
                : null;
        obj.linkedToProjects = jsonObject['linked_to_projects'];
        obj.roleId =
            'role_id' in jsonObject && jsonObject['role_id'] != null
                ? (jsonObject['role_id'] as number)
                : null;
        obj.roleCode =
            'role_code' in jsonObject && jsonObject['role_code'] != null
                ? (jsonObject['role_code'] as string)
                : null;
        obj.roleTitle =
            'role_title' in jsonObject && jsonObject['role_title'] != null
                ? (jsonObject['role_title'] as string)
                : null;
        obj.highlights = jsonObject['highlights'];
        obj.hiredAt =
            'hired_at' in jsonObject && jsonObject['hired_at'] != null
                ? Igor.Json.DateTimeSerializer.fromJson(jsonObject['hired_at'])
                : null;
        obj.firedAt =
            'fired_at' in jsonObject && jsonObject['fired_at'] != null
                ? Igor.Json.DateTimeSerializer.fromJson(jsonObject['fired_at'])
                : null;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: PersonnelAccount): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['username'] = value.username;
        if (value.name != null) result['name'] = value.name;
        if (value.email != null) result['email'] = value.email;
        if (value.phone != null) result['phone'] = value.phone;
        if (value.officeId != null) result['office_id'] = value.officeId;
        if (value.officeName != null) result['office_name'] = value.officeName;
        if (value.officeCountryAlpha2 != null)
            result['office_country_alpha2'] = value.officeCountryAlpha2;
        if (value.officeCountryName != null)
            result['office_country_name'] = value.officeCountryName;
        if (value.department != null) result['department'] = value.department;
        if (value.jobTitle != null) result['job_title'] = value.jobTitle;
        result['is_blocked'] = value.isBlocked;
        result['is_deleted'] = value.isDeleted;
        result['is_superadmin'] = value.isSuperadmin;
        result['is_office_manager'] = value.isOfficeManager;
        if (value.supervisorId != null) result['supervisor_id'] = value.supervisorId;
        if (value.location != null) result['location'] = value.location;
        if (value.supervisorUsername != null)
            result['supervisor_username'] = value.supervisorUsername;
        if (value.supervisorName != null) result['supervisor_name'] = value.supervisorName;
        if (value.allocatedToProjectId != null)
            result['allocated_to_project_id'] = value.allocatedToProjectId;
        if (value.allocatedToProjectName != null)
            result['allocated_to_project_name'] = value.allocatedToProjectName;
        result['linked_to_projects'] = value.linkedToProjects;
        if (value.roleId != null) result['role_id'] = value.roleId;
        if (value.roleCode != null) result['role_code'] = value.roleCode;
        if (value.roleTitle != null) result['role_title'] = value.roleTitle;
        result['highlights'] = value.highlights;
        if (value.hiredAt != null)
            result['hired_at'] = Igor.Json.DateTimeSerializer.toJson(value.hiredAt);
        if (value.firedAt != null)
            result['fired_at'] = Igor.Json.DateTimeSerializer.toJson(value.firedAt);
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelAccount.toJson(this);
    }
}

export class PersonnelAccountRole {
    personnelId!: number;
    username!: string;
    projectId!: number;
    projectName!: string;
    groupRoles?: { [key: string]: AccessRoleObject } | null = null;
    userRole?: AccessRole | null = null;

    static fromJson(json: Igor.Json.JsonValue): PersonnelAccountRole {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelAccountRole();
        obj.personnelId = jsonObject['personnel_id'] as number;
        obj.username = jsonObject['username'] as string;
        obj.projectId = jsonObject['project_id'] as number;
        obj.projectName = jsonObject['project_name'] as string;
        obj.groupRoles =
            'group_roles' in jsonObject && jsonObject['group_roles'] != null
                ? Igor.Json.Dict(AccessRoleObject).fromJson(jsonObject['group_roles'])
                : null;
        obj.userRole =
            'user_role' in jsonObject && jsonObject['user_role'] != null
                ? AccessRole.fromJson(jsonObject['user_role'])
                : null;
        return obj;
    }

    static toJson(value: PersonnelAccountRole): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['personnel_id'] = value.personnelId;
        result['username'] = value.username;
        result['project_id'] = value.projectId;
        result['project_name'] = value.projectName;
        if (value.groupRoles != null)
            result['group_roles'] = Igor.Json.Dict(AccessRoleObject).toJson(value.groupRoles);
        if (value.userRole != null) result['user_role'] = AccessRole.toJson(value.userRole);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelAccountRole.toJson(this);
    }
}

export class PersonnelGroup {
    id!: number;
    rev!: number;
    name!: string;
    description?: string | null = null;
    isDeleted!: boolean;
    members!: Array<string>;
    memberCount!: number;
    isSuperadmin!: boolean;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): PersonnelGroup {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelGroup();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.name = jsonObject['name'] as string;
        obj.description =
            'description' in jsonObject && jsonObject['description'] != null
                ? (jsonObject['description'] as string)
                : null;
        obj.isDeleted = jsonObject['is_deleted'] as boolean;
        obj.members = Igor.Json.List(Igor.Json.String).fromJson(jsonObject['members']);
        obj.memberCount = jsonObject['member_count'] as number;
        obj.isSuperadmin = jsonObject['is_superadmin'] as boolean;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: PersonnelGroup): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['name'] = value.name;
        if (value.description != null) result['description'] = value.description;
        result['is_deleted'] = value.isDeleted;
        result['members'] = Igor.Json.List(Igor.Json.String).toJson(value.members);
        result['member_count'] = value.memberCount;
        result['is_superadmin'] = value.isSuperadmin;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelGroup.toJson(this);
    }
}

export class PersonnelGroupRole {
    groupId!: number;
    groupName!: string;
    projectId!: number;
    projectName!: string;
    groupRole?: AccessRole | null = null;

    static fromJson(json: Igor.Json.JsonValue): PersonnelGroupRole {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelGroupRole();
        obj.groupId = jsonObject['group_id'] as number;
        obj.groupName = jsonObject['group_name'] as string;
        obj.projectId = jsonObject['project_id'] as number;
        obj.projectName = jsonObject['project_name'] as string;
        obj.groupRole =
            'group_role' in jsonObject && jsonObject['group_role'] != null
                ? AccessRole.fromJson(jsonObject['group_role'])
                : null;
        return obj;
    }

    static toJson(value: PersonnelGroupRole): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['group_id'] = value.groupId;
        result['group_name'] = value.groupName;
        result['project_id'] = value.projectId;
        result['project_name'] = value.projectName;
        if (value.groupRole != null) result['group_role'] = AccessRole.toJson(value.groupRole);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelGroupRole.toJson(this);
    }
}

export class PersonnelSession {
    id!: string;
    personnelId!: number;
    username!: string;
    createdAt!: Date;
    validThru!: Date;

    static fromJson(json: Igor.Json.JsonValue): PersonnelSession {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new PersonnelSession();
        obj.id = jsonObject['id'] as string;
        obj.personnelId = jsonObject['personnel_id'] as number;
        obj.username = jsonObject['username'] as string;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.validThru = Igor.Json.DateTimeSerializer.fromJson(jsonObject['valid_thru']);
        return obj;
    }

    static toJson(value: PersonnelSession): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['personnel_id'] = value.personnelId;
        result['username'] = value.username;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['valid_thru'] = Igor.Json.DateTimeSerializer.toJson(value.validThru);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return PersonnelSession.toJson(this);
    }
}

export class Country {
    id!: number;
    name!: string;
    alpha2!: string;
    alpha3!: string;
    createdAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): Country {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new Country();
        obj.id = jsonObject['id'] as number;
        obj.name = jsonObject['name'] as string;
        obj.alpha2 = jsonObject['alpha2'] as string;
        obj.alpha3 = jsonObject['alpha3'] as string;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        return obj;
    }

    static toJson(value: Country): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['name'] = value.name;
        result['alpha2'] = value.alpha2;
        result['alpha3'] = value.alpha3;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return Country.toJson(this);
    }
}

export class Office {
    id!: number;
    rev!: number;
    name!: string;
    countryId!: number;
    countryAlpha2!: string;
    countryName!: string;
    city?: string | null = null;
    address?: string | null = null;
    postalCode?: string | null = null;
    groupId?: number | null = null;
    groupName?: string | null = null;
    allowedRoles!: Array<number>;
    vismaCountry?: string | null = null;
    vismaCompanyId?: string | null = null;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): Office {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new Office();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.name = jsonObject['name'] as string;
        obj.countryId = jsonObject['country_id'] as number;
        obj.countryAlpha2 = jsonObject['country_alpha2'] as string;
        obj.countryName = jsonObject['country_name'] as string;
        obj.city =
            'city' in jsonObject && jsonObject['city'] != null
                ? (jsonObject['city'] as string)
                : null;
        obj.address =
            'address' in jsonObject && jsonObject['address'] != null
                ? (jsonObject['address'] as string)
                : null;
        obj.postalCode =
            'postal_code' in jsonObject && jsonObject['postal_code'] != null
                ? (jsonObject['postal_code'] as string)
                : null;
        obj.groupId =
            'group_id' in jsonObject && jsonObject['group_id'] != null
                ? (jsonObject['group_id'] as number)
                : null;
        obj.groupName =
            'group_name' in jsonObject && jsonObject['group_name'] != null
                ? (jsonObject['group_name'] as string)
                : null;
        obj.allowedRoles = Igor.Json.List(Igor.Json.Number).fromJson(jsonObject['allowed_roles']);
        obj.vismaCountry =
            'visma_country' in jsonObject && jsonObject['visma_country'] != null
                ? (jsonObject['visma_country'] as string)
                : null;
        obj.vismaCompanyId =
            'visma_company_id' in jsonObject && jsonObject['visma_company_id'] != null
                ? (jsonObject['visma_company_id'] as string)
                : null;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: Office): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['name'] = value.name;
        result['country_id'] = value.countryId;
        result['country_alpha2'] = value.countryAlpha2;
        result['country_name'] = value.countryName;
        if (value.city != null) result['city'] = value.city;
        if (value.address != null) result['address'] = value.address;
        if (value.postalCode != null) result['postal_code'] = value.postalCode;
        if (value.groupId != null) result['group_id'] = value.groupId;
        if (value.groupName != null) result['group_name'] = value.groupName;
        result['allowed_roles'] = Igor.Json.List(Igor.Json.Number).toJson(value.allowedRoles);
        if (value.vismaCountry != null) result['visma_country'] = value.vismaCountry;
        if (value.vismaCompanyId != null) result['visma_company_id'] = value.vismaCompanyId;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return Office.toJson(this);
    }
}

export class Project {
    id!: number;
    rev!: number;
    title!: string;
    key!: string;
    color?: string | null = null;
    supervisorId?: number | null = null;
    supervisorUsername?: string | null = null;
    supervisorName?: string | null = null;
    leadingOfficeId!: number;
    leadingOfficeName!: string;
    financeCode!: string;
    invoiceable!: boolean;
    isArchived: boolean = false;
    taskCode!: TaskKind;
    startedAt?: Date | null = null;
    finishedAt?: Date | null = null;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): Project {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new Project();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.title = jsonObject['title'] as string;
        obj.key = jsonObject['key'] as string;
        obj.color =
            'color' in jsonObject && jsonObject['color'] != null
                ? (jsonObject['color'] as string)
                : null;
        obj.supervisorId =
            'supervisor_id' in jsonObject && jsonObject['supervisor_id'] != null
                ? (jsonObject['supervisor_id'] as number)
                : null;
        obj.supervisorUsername =
            'supervisor_username' in jsonObject && jsonObject['supervisor_username'] != null
                ? (jsonObject['supervisor_username'] as string)
                : null;
        obj.supervisorName =
            'supervisor_name' in jsonObject && jsonObject['supervisor_name'] != null
                ? (jsonObject['supervisor_name'] as string)
                : null;
        obj.leadingOfficeId = jsonObject['leading_office_id'] as number;
        obj.leadingOfficeName = jsonObject['leading_office_name'] as string;
        obj.financeCode = jsonObject['finance_code'] as string;
        obj.invoiceable = jsonObject['invoiceable'] as boolean;
        obj.isArchived =
            'is_archived' in jsonObject && jsonObject['is_archived'] != null
                ? (jsonObject['is_archived'] as boolean)
                : false;
        obj.taskCode = TaskKind.fromJson(jsonObject['task_code']);
        obj.startedAt =
            'started_at' in jsonObject && jsonObject['started_at'] != null
                ? Igor.Json.DateTimeSerializer.fromJson(jsonObject['started_at'])
                : null;
        obj.finishedAt =
            'finished_at' in jsonObject && jsonObject['finished_at'] != null
                ? Igor.Json.DateTimeSerializer.fromJson(jsonObject['finished_at'])
                : null;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: Project): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['title'] = value.title;
        result['key'] = value.key;
        if (value.color != null) result['color'] = value.color;
        if (value.supervisorId != null) result['supervisor_id'] = value.supervisorId;
        if (value.supervisorUsername != null)
            result['supervisor_username'] = value.supervisorUsername;
        if (value.supervisorName != null) result['supervisor_name'] = value.supervisorName;
        result['leading_office_id'] = value.leadingOfficeId;
        result['leading_office_name'] = value.leadingOfficeName;
        result['finance_code'] = value.financeCode;
        result['invoiceable'] = value.invoiceable;
        result['is_archived'] = value.isArchived;
        result['task_code'] = TaskKind.toJson(value.taskCode);
        if (value.startedAt != null)
            result['started_at'] = Igor.Json.DateTimeSerializer.toJson(value.startedAt);
        if (value.finishedAt != null)
            result['finished_at'] = Igor.Json.DateTimeSerializer.toJson(value.finishedAt);
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return Project.toJson(this);
    }
}

export enum TimeOffKind {
    /** Vacation */
    Vacation = 1,
    /** Vacation Paid */
    PaidVacation = 2,
    /** Vacation Unpaid */
    UnpaidVacation = 3,
    /** Absence */
    Absence = 4,
    /** Travel */
    Travel = 5,
    /** Care of Child */
    Vab = 6,
    /** Sick Paid */
    Sick = 7,
    /** Sick Unpaid */
    UnpaidSick = 8,
    /** Bank Day / Holiday */
    Holiday = 9,
    /** Empty */
    Empty = 10,
    /** Leave Parental */
    ParentalLeave = 11,
    /** Leave Maternity */
    MaternityLeave = 12,
    /** Time Off */
    TimeOff = 13,
    /** Leave Temporary */
    TempLeave = 14
}

export namespace TimeOffKind {
    export function toJson(value: TimeOffKind): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): TimeOffKind {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: TimeOffKind): Igor.Json.JsonValue {
        switch (value) {
            case TimeOffKind.Vacation:
                return 'vacation';
            case TimeOffKind.PaidVacation:
                return 'paid_vacation';
            case TimeOffKind.UnpaidVacation:
                return 'unpaid_vacation';
            case TimeOffKind.Absence:
                return 'absence';
            case TimeOffKind.Travel:
                return 'travel';
            case TimeOffKind.Vab:
                return 'vab';
            case TimeOffKind.Sick:
                return 'sick';
            case TimeOffKind.UnpaidSick:
                return 'unpaid_sick';
            case TimeOffKind.Holiday:
                return 'holiday';
            case TimeOffKind.Empty:
                return 'empty';
            case TimeOffKind.ParentalLeave:
                return 'parental_leave';
            case TimeOffKind.MaternityLeave:
                return 'maternity_leave';
            case TimeOffKind.TimeOff:
                return 'time_off';
            case TimeOffKind.TempLeave:
                return 'temp_leave';
            default:
                throw new Error(`Invalid TimeOffKind value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): TimeOffKind {
        switch (json) {
            case 'vacation':
                return TimeOffKind.Vacation;
            case 'paid_vacation':
                return TimeOffKind.PaidVacation;
            case 'unpaid_vacation':
                return TimeOffKind.UnpaidVacation;
            case 'absence':
                return TimeOffKind.Absence;
            case 'travel':
                return TimeOffKind.Travel;
            case 'vab':
                return TimeOffKind.Vab;
            case 'sick':
                return TimeOffKind.Sick;
            case 'unpaid_sick':
                return TimeOffKind.UnpaidSick;
            case 'holiday':
                return TimeOffKind.Holiday;
            case 'empty':
                return TimeOffKind.Empty;
            case 'parental_leave':
                return TimeOffKind.ParentalLeave;
            case 'maternity_leave':
                return TimeOffKind.MaternityLeave;
            case 'time_off':
                return TimeOffKind.TimeOff;
            case 'temp_leave':
                return TimeOffKind.TempLeave;
            default:
                throw new Error(`Invalid TimeOffKind value: ${json}`);
        }
    }

    export function getDescription(value: TimeOffKind): string {
        switch (value) {
            case TimeOffKind.Vacation:
                return 'Vacation';
            case TimeOffKind.PaidVacation:
                return 'Vacation Paid';
            case TimeOffKind.UnpaidVacation:
                return 'Vacation Unpaid';
            case TimeOffKind.Absence:
                return 'Absence';
            case TimeOffKind.Travel:
                return 'Travel';
            case TimeOffKind.Vab:
                return 'Care of Child';
            case TimeOffKind.Sick:
                return 'Sick Paid';
            case TimeOffKind.UnpaidSick:
                return 'Sick Unpaid';
            case TimeOffKind.Holiday:
                return 'Bank Day / Holiday';
            case TimeOffKind.Empty:
                return 'Empty';
            case TimeOffKind.ParentalLeave:
                return 'Leave Parental';
            case TimeOffKind.MaternityLeave:
                return 'Leave Maternity';
            case TimeOffKind.TimeOff:
                return 'Time Off';
            case TimeOffKind.TempLeave:
                return 'Leave Temporary';
            default:
                return '';
        }
    }
}

export enum TaskKind {
    /** Project */
    Project = 1,
    /** Continue Development */
    ContDev = 2,
    /** Research & Development */
    Rnd = 3
}

export namespace TaskKind {
    export function toJson(value: TaskKind): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): TaskKind {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: TaskKind): Igor.Json.JsonValue {
        switch (value) {
            case TaskKind.Project:
                return 'project';
            case TaskKind.ContDev:
                return 'cont_dev';
            case TaskKind.Rnd:
                return 'rnd';
            default:
                throw new Error(`Invalid TaskKind value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): TaskKind {
        switch (json) {
            case 'project':
                return TaskKind.Project;
            case 'cont_dev':
                return TaskKind.ContDev;
            case 'rnd':
                return TaskKind.Rnd;
            default:
                throw new Error(`Invalid TaskKind value: ${json}`);
        }
    }

    export function getDescription(value: TaskKind): string {
        switch (value) {
            case TaskKind.Project:
                return 'Project';
            case TaskKind.ContDev:
                return 'Continue Development';
            case TaskKind.Rnd:
                return 'Research & Development';
            default:
                return '';
        }
    }
}

export class TimesheetCell {
    id!: number;
    personnelId!: number;
    personnelUsername!: string;
    personnelName!: string;
    isProtected!: boolean;
    projectId?: number | null = null;
    projectName?: string | null = null;
    timeOff?: TimeOffKind | null = null;
    cellDateIso!: string;
    cellDate!: Date;
    comment?: string | null = null;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): TimesheetCell {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new TimesheetCell();
        obj.id = jsonObject['id'] as number;
        obj.personnelId = jsonObject['personnel_id'] as number;
        obj.personnelUsername = jsonObject['personnel_username'] as string;
        obj.personnelName = jsonObject['personnel_name'] as string;
        obj.isProtected = jsonObject['is_protected'] as boolean;
        obj.projectId =
            'project_id' in jsonObject && jsonObject['project_id'] != null
                ? (jsonObject['project_id'] as number)
                : null;
        obj.projectName =
            'project_name' in jsonObject && jsonObject['project_name'] != null
                ? (jsonObject['project_name'] as string)
                : null;
        obj.timeOff =
            'time_off' in jsonObject && jsonObject['time_off'] != null
                ? TimeOffKind.fromJson(jsonObject['time_off'])
                : null;
        obj.cellDateIso = jsonObject['cell_date_iso'] as string;
        obj.cellDate = Igor.Json.DateTimeSerializer.fromJson(jsonObject['cell_date']);
        obj.comment =
            'comment' in jsonObject && jsonObject['comment'] != null
                ? (jsonObject['comment'] as string)
                : null;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: TimesheetCell): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['personnel_id'] = value.personnelId;
        result['personnel_username'] = value.personnelUsername;
        result['personnel_name'] = value.personnelName;
        result['is_protected'] = value.isProtected;
        if (value.projectId != null) result['project_id'] = value.projectId;
        if (value.projectName != null) result['project_name'] = value.projectName;
        if (value.timeOff != null) result['time_off'] = TimeOffKind.toJson(value.timeOff);
        result['cell_date_iso'] = value.cellDateIso;
        result['cell_date'] = Igor.Json.DateTimeSerializer.toJson(value.cellDate);
        if (value.comment != null) result['comment'] = value.comment;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return TimesheetCell.toJson(this);
    }
}

export class Role {
    id!: number;
    rev!: number;
    code!: string;
    title!: string;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): Role {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new Role();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.code = jsonObject['code'] as string;
        obj.title = jsonObject['title'] as string;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: Role): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['code'] = value.code;
        result['title'] = value.title;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return Role.toJson(this);
    }
}

export class Team {
    id!: number;
    rev!: number;
    title!: string;
    members!: Array<string>;
    createdBy?: number | null = null;
    createdByUsername?: string | null = null;
    createdByName?: string | null = null;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): Team {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new Team();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.title = jsonObject['title'] as string;
        obj.members = Igor.Json.List(Igor.Json.String).fromJson(jsonObject['members']);
        obj.createdBy =
            'created_by' in jsonObject && jsonObject['created_by'] != null
                ? (jsonObject['created_by'] as number)
                : null;
        obj.createdByUsername =
            'created_by_username' in jsonObject && jsonObject['created_by_username'] != null
                ? (jsonObject['created_by_username'] as string)
                : null;
        obj.createdByName =
            'created_by_name' in jsonObject && jsonObject['created_by_name'] != null
                ? (jsonObject['created_by_name'] as string)
                : null;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: Team): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['title'] = value.title;
        result['members'] = Igor.Json.List(Igor.Json.String).toJson(value.members);
        if (value.createdBy != null) result['created_by'] = value.createdBy;
        if (value.createdByUsername != null)
            result['created_by_username'] = value.createdByUsername;
        if (value.createdByName != null) result['created_by_name'] = value.createdByName;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return Team.toJson(this);
    }
}

export enum HistoryActor {
    User = 1,
    Robot = 2,
    Anonymous = 3
}

export namespace HistoryActor {
    export function toJson(value: HistoryActor): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): HistoryActor {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: HistoryActor): Igor.Json.JsonValue {
        switch (value) {
            case HistoryActor.User:
                return 'user';
            case HistoryActor.Robot:
                return 'robot';
            case HistoryActor.Anonymous:
                return 'anonymous';
            default:
                throw new Error(`Invalid HistoryActor value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): HistoryActor {
        switch (json) {
            case 'user':
                return HistoryActor.User;
            case 'robot':
                return HistoryActor.Robot;
            case 'anonymous':
                return HistoryActor.Anonymous;
            default:
                throw new Error(`Invalid HistoryActor value: ${json}`);
        }
    }

    export function getDescription(value: HistoryActor): string {
        switch (value) {
            case HistoryActor.User:
                return '';
            case HistoryActor.Robot:
                return '';
            case HistoryActor.Anonymous:
                return '';
            default:
                return '';
        }
    }
}

export enum HistoryEntity {
    Auth = 1,
    Session = 2,
    Settings = 3,
    User = 4,
    Group = 5,
    GroupMembership = 6,
    Country = 7,
    Role = 8,
    Office = 9,
    Project = 10,
    Team = 11,
    TeamMembership = 12,
    Timecell = 13
}

export namespace HistoryEntity {
    export function toJson(value: HistoryEntity): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): HistoryEntity {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: HistoryEntity): Igor.Json.JsonValue {
        switch (value) {
            case HistoryEntity.Auth:
                return 'auth';
            case HistoryEntity.Session:
                return 'session';
            case HistoryEntity.Settings:
                return 'settings';
            case HistoryEntity.User:
                return 'user';
            case HistoryEntity.Group:
                return 'group';
            case HistoryEntity.GroupMembership:
                return 'group_membership';
            case HistoryEntity.Country:
                return 'country';
            case HistoryEntity.Role:
                return 'role';
            case HistoryEntity.Office:
                return 'office';
            case HistoryEntity.Project:
                return 'project';
            case HistoryEntity.Team:
                return 'team';
            case HistoryEntity.TeamMembership:
                return 'team_membership';
            case HistoryEntity.Timecell:
                return 'timecell';
            default:
                throw new Error(`Invalid HistoryEntity value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): HistoryEntity {
        switch (json) {
            case 'auth':
                return HistoryEntity.Auth;
            case 'session':
                return HistoryEntity.Session;
            case 'settings':
                return HistoryEntity.Settings;
            case 'user':
                return HistoryEntity.User;
            case 'group':
                return HistoryEntity.Group;
            case 'group_membership':
                return HistoryEntity.GroupMembership;
            case 'country':
                return HistoryEntity.Country;
            case 'role':
                return HistoryEntity.Role;
            case 'office':
                return HistoryEntity.Office;
            case 'project':
                return HistoryEntity.Project;
            case 'team':
                return HistoryEntity.Team;
            case 'team_membership':
                return HistoryEntity.TeamMembership;
            case 'timecell':
                return HistoryEntity.Timecell;
            default:
                throw new Error(`Invalid HistoryEntity value: ${json}`);
        }
    }

    export function getDescription(value: HistoryEntity): string {
        switch (value) {
            case HistoryEntity.Auth:
                return '';
            case HistoryEntity.Session:
                return '';
            case HistoryEntity.Settings:
                return '';
            case HistoryEntity.User:
                return '';
            case HistoryEntity.Group:
                return '';
            case HistoryEntity.GroupMembership:
                return '';
            case HistoryEntity.Country:
                return '';
            case HistoryEntity.Role:
                return '';
            case HistoryEntity.Office:
                return '';
            case HistoryEntity.Project:
                return '';
            case HistoryEntity.Team:
                return '';
            case HistoryEntity.TeamMembership:
                return '';
            case HistoryEntity.Timecell:
                return '';
            default:
                return '';
        }
    }
}

export enum HistoryOperation {
    Create = 1,
    Read = 2,
    Update = 3,
    Delete = 4,
    Undelete = 5,
    Block = 6,
    Unblock = 7,
    Login = 8,
    Logout = 9,
    Allocate = 10,
    Deallocate = 11,
    Protect = 12,
    Unprotect = 13,
    Absence = 14
}

export namespace HistoryOperation {
    export function toJson(value: HistoryOperation): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): HistoryOperation {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: HistoryOperation): Igor.Json.JsonValue {
        switch (value) {
            case HistoryOperation.Create:
                return 'create';
            case HistoryOperation.Read:
                return 'read';
            case HistoryOperation.Update:
                return 'update';
            case HistoryOperation.Delete:
                return 'delete';
            case HistoryOperation.Undelete:
                return 'undelete';
            case HistoryOperation.Block:
                return 'block';
            case HistoryOperation.Unblock:
                return 'unblock';
            case HistoryOperation.Login:
                return 'login';
            case HistoryOperation.Logout:
                return 'logout';
            case HistoryOperation.Allocate:
                return 'allocate';
            case HistoryOperation.Deallocate:
                return 'deallocate';
            case HistoryOperation.Protect:
                return 'protect';
            case HistoryOperation.Unprotect:
                return 'unprotect';
            case HistoryOperation.Absence:
                return 'absence';
            default:
                throw new Error(`Invalid HistoryOperation value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): HistoryOperation {
        switch (json) {
            case 'create':
                return HistoryOperation.Create;
            case 'read':
                return HistoryOperation.Read;
            case 'update':
                return HistoryOperation.Update;
            case 'delete':
                return HistoryOperation.Delete;
            case 'undelete':
                return HistoryOperation.Undelete;
            case 'block':
                return HistoryOperation.Block;
            case 'unblock':
                return HistoryOperation.Unblock;
            case 'login':
                return HistoryOperation.Login;
            case 'logout':
                return HistoryOperation.Logout;
            case 'allocate':
                return HistoryOperation.Allocate;
            case 'deallocate':
                return HistoryOperation.Deallocate;
            case 'protect':
                return HistoryOperation.Protect;
            case 'unprotect':
                return HistoryOperation.Unprotect;
            case 'absence':
                return HistoryOperation.Absence;
            default:
                throw new Error(`Invalid HistoryOperation value: ${json}`);
        }
    }

    export function getDescription(value: HistoryOperation): string {
        switch (value) {
            case HistoryOperation.Create:
                return '';
            case HistoryOperation.Read:
                return '';
            case HistoryOperation.Update:
                return '';
            case HistoryOperation.Delete:
                return '';
            case HistoryOperation.Undelete:
                return '';
            case HistoryOperation.Block:
                return '';
            case HistoryOperation.Unblock:
                return '';
            case HistoryOperation.Login:
                return '';
            case HistoryOperation.Logout:
                return '';
            case HistoryOperation.Allocate:
                return '';
            case HistoryOperation.Deallocate:
                return '';
            case HistoryOperation.Protect:
                return '';
            case HistoryOperation.Unprotect:
                return '';
            case HistoryOperation.Absence:
                return '';
            default:
                return '';
        }
    }
}

export class HistoryEntry {
    id!: number;
    actor!: HistoryActor;
    actorId?: number | null = null;
    actorName?: string | null = null;
    actorUsername?: string | null = null;
    entity!: HistoryEntity;
    entityId?: number | null = null;
    entityParam?: string | null = null;
    operation!: HistoryOperation;
    isBulk!: boolean;
    properties!: Igor.Json.JsonValue;
    result!: boolean;
    comment?: string | null = null;
    createdAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): HistoryEntry {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new HistoryEntry();
        obj.id = jsonObject['id'] as number;
        obj.actor = HistoryActor.fromJson(jsonObject['actor']);
        obj.actorId =
            'actor_id' in jsonObject && jsonObject['actor_id'] != null
                ? (jsonObject['actor_id'] as number)
                : null;
        obj.actorName =
            'actor_name' in jsonObject && jsonObject['actor_name'] != null
                ? (jsonObject['actor_name'] as string)
                : null;
        obj.actorUsername =
            'actor_username' in jsonObject && jsonObject['actor_username'] != null
                ? (jsonObject['actor_username'] as string)
                : null;
        obj.entity = HistoryEntity.fromJson(jsonObject['entity']);
        obj.entityId =
            'entity_id' in jsonObject && jsonObject['entity_id'] != null
                ? (jsonObject['entity_id'] as number)
                : null;
        obj.entityParam =
            'entity_param' in jsonObject && jsonObject['entity_param'] != null
                ? (jsonObject['entity_param'] as string)
                : null;
        obj.operation = HistoryOperation.fromJson(jsonObject['operation']);
        obj.isBulk = jsonObject['is_bulk'] as boolean;
        obj.properties = jsonObject['properties'];
        obj.result = jsonObject['result'] as boolean;
        obj.comment =
            'comment' in jsonObject && jsonObject['comment'] != null
                ? (jsonObject['comment'] as string)
                : null;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        return obj;
    }

    static toJson(value: HistoryEntry): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['actor'] = HistoryActor.toJson(value.actor);
        if (value.actorId != null) result['actor_id'] = value.actorId;
        if (value.actorName != null) result['actor_name'] = value.actorName;
        if (value.actorUsername != null) result['actor_username'] = value.actorUsername;
        result['entity'] = HistoryEntity.toJson(value.entity);
        if (value.entityId != null) result['entity_id'] = value.entityId;
        if (value.entityParam != null) result['entity_param'] = value.entityParam;
        result['operation'] = HistoryOperation.toJson(value.operation);
        result['is_bulk'] = value.isBulk;
        result['properties'] = value.properties;
        result['result'] = value.result;
        if (value.comment != null) result['comment'] = value.comment;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return HistoryEntry.toJson(this);
    }
}

export enum ReportStatus {
    Created = 1,
    Running = 2,
    Stopped = 3,
    Completed = 4,
    Error = 5,
    Scheduled = 6
}

export namespace ReportStatus {
    export function toJson(value: ReportStatus): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): ReportStatus {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: ReportStatus): Igor.Json.JsonValue {
        switch (value) {
            case ReportStatus.Created:
                return 'created';
            case ReportStatus.Running:
                return 'running';
            case ReportStatus.Stopped:
                return 'stopped';
            case ReportStatus.Completed:
                return 'completed';
            case ReportStatus.Error:
                return 'error';
            case ReportStatus.Scheduled:
                return 'scheduled';
            default:
                throw new Error(`Invalid ReportStatus value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): ReportStatus {
        switch (json) {
            case 'created':
                return ReportStatus.Created;
            case 'running':
                return ReportStatus.Running;
            case 'stopped':
                return ReportStatus.Stopped;
            case 'completed':
                return ReportStatus.Completed;
            case 'error':
                return ReportStatus.Error;
            case 'scheduled':
                return ReportStatus.Scheduled;
            default:
                throw new Error(`Invalid ReportStatus value: ${json}`);
        }
    }

    export function getDescription(value: ReportStatus): string {
        switch (value) {
            case ReportStatus.Created:
                return '';
            case ReportStatus.Running:
                return '';
            case ReportStatus.Stopped:
                return '';
            case ReportStatus.Completed:
                return '';
            case ReportStatus.Error:
                return '';
            case ReportStatus.Scheduled:
                return '';
            default:
                return '';
        }
    }
}

export class VismaReport {
    id!: number;
    officeId!: number;
    officeName!: string;
    year!: number;
    month!: number;
    comment!: string;
    omitIds?: Array<number> | null = [];
    omitUids?: Array<string> | null = [];
    createdBy!: number;
    createdByUsername!: string;
    createdByName!: string;
    updatedBy?: number | null = null;
    updatedByUsername?: string | null = null;
    updatedByName?: string | null = null;
    deliveryTaskId?: string | null = null;
    deliveryData?: Igor.Json.JsonValue | null = null;
    deliveryStatus?: ReportStatus | null = null;
    deliveredAt?: Date | null = null;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): VismaReport {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new VismaReport();
        obj.id = jsonObject['id'] as number;
        obj.officeId = jsonObject['office_id'] as number;
        obj.officeName = jsonObject['office_name'] as string;
        obj.year = jsonObject['year'] as number;
        obj.month = jsonObject['month'] as number;
        obj.comment = jsonObject['comment'] as string;
        obj.omitIds =
            'omit_ids' in jsonObject && jsonObject['omit_ids'] != null
                ? Igor.Json.List(Igor.Json.Number).fromJson(jsonObject['omit_ids'])
                : [];
        obj.omitUids =
            'omit_uids' in jsonObject && jsonObject['omit_uids'] != null
                ? Igor.Json.List(Igor.Json.String).fromJson(jsonObject['omit_uids'])
                : [];
        obj.createdBy = jsonObject['created_by'] as number;
        obj.createdByUsername = jsonObject['created_by_username'] as string;
        obj.createdByName = jsonObject['created_by_name'] as string;
        obj.updatedBy =
            'updated_by' in jsonObject && jsonObject['updated_by'] != null
                ? (jsonObject['updated_by'] as number)
                : null;
        obj.updatedByUsername =
            'updated_by_username' in jsonObject && jsonObject['updated_by_username'] != null
                ? (jsonObject['updated_by_username'] as string)
                : null;
        obj.updatedByName =
            'updated_by_name' in jsonObject && jsonObject['updated_by_name'] != null
                ? (jsonObject['updated_by_name'] as string)
                : null;
        obj.deliveryTaskId =
            'delivery_task_id' in jsonObject && jsonObject['delivery_task_id'] != null
                ? (jsonObject['delivery_task_id'] as string)
                : null;
        obj.deliveryData =
            'delivery_data' in jsonObject && jsonObject['delivery_data'] != null
                ? jsonObject['delivery_data']
                : null;
        obj.deliveryStatus =
            'delivery_status' in jsonObject && jsonObject['delivery_status'] != null
                ? ReportStatus.fromJson(jsonObject['delivery_status'])
                : null;
        obj.deliveredAt =
            'delivered_at' in jsonObject && jsonObject['delivered_at'] != null
                ? Igor.Json.DateTimeSerializer.fromJson(jsonObject['delivered_at'])
                : null;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: VismaReport): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['office_id'] = value.officeId;
        result['office_name'] = value.officeName;
        result['year'] = value.year;
        result['month'] = value.month;
        result['comment'] = value.comment;
        if (value.omitIds != null)
            result['omit_ids'] = Igor.Json.List(Igor.Json.Number).toJson(value.omitIds);
        if (value.omitUids != null)
            result['omit_uids'] = Igor.Json.List(Igor.Json.String).toJson(value.omitUids);
        result['created_by'] = value.createdBy;
        result['created_by_username'] = value.createdByUsername;
        result['created_by_name'] = value.createdByName;
        if (value.updatedBy != null) result['updated_by'] = value.updatedBy;
        if (value.updatedByUsername != null)
            result['updated_by_username'] = value.updatedByUsername;
        if (value.updatedByName != null) result['updated_by_name'] = value.updatedByName;
        if (value.deliveryTaskId != null) result['delivery_task_id'] = value.deliveryTaskId;
        if (value.deliveryData != null) result['delivery_data'] = value.deliveryData;
        if (value.deliveryStatus != null)
            result['delivery_status'] = ReportStatus.toJson(value.deliveryStatus);
        if (value.deliveredAt != null)
            result['delivered_at'] = Igor.Json.DateTimeSerializer.toJson(value.deliveredAt);
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return VismaReport.toJson(this);
    }
}

export class Highlight {
    id!: number;
    rev!: number;
    code!: string;
    title!: string;
    createdAt!: Date;
    updatedAt!: Date;

    static fromJson(json: Igor.Json.JsonValue): Highlight {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new Highlight();
        obj.id = jsonObject['id'] as number;
        obj.rev = jsonObject['rev'] as number;
        obj.code = jsonObject['code'] as string;
        obj.title = jsonObject['title'] as string;
        obj.createdAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['created_at']);
        obj.updatedAt = Igor.Json.DateTimeSerializer.fromJson(jsonObject['updated_at']);
        return obj;
    }

    static toJson(value: Highlight): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['id'] = value.id;
        result['rev'] = value.rev;
        result['code'] = value.code;
        result['title'] = value.title;
        result['created_at'] = Igor.Json.DateTimeSerializer.toJson(value.createdAt);
        result['updated_at'] = Igor.Json.DateTimeSerializer.toJson(value.updatedAt);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return Highlight.toJson(this);
    }
}
