// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DataProtocol from './data-protocol';
import * as DbProtocol from './db-protocol';
import * as WebProtocol from './web-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesHistoryService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getHistory(
        entity: string,
        needle: string | null = null,
        orderBy: WebProtocol.HistoryEntryOrderBy,
        orderDir: DataProtocol.OrderDirection,
        offset: number,
        limit: number
    ): Observable<DataProtocol.CollectionSlice<DbProtocol.HistoryEntry>> {
        const queryParams: Array<string> = [];
        if (needle != null) queryParams.push(`needle=${needle}`);
        queryParams.push(`order_by=${WebProtocol.HistoryEntryOrderBy.toJson(orderBy)}`);
        queryParams.push(`order_dir=${DataProtocol.OrderDirection.toJson(orderDir)}`);
        queryParams.push(`offset=${offset}`);
        queryParams.push(`limit=${limit}`);
        const queryString = queryParams.length > 0 ? `?${queryParams.join('&')}` : '';

        return this.http
            .get(`${this.baseUrl}/api/history/${entity}${queryString}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.CollectionSlice.instanceJsonSerializer<DbProtocol.HistoryEntry>(
                                DbProtocol.HistoryEntry
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getEmployeeRoleChangeHistory(
        personnelId: number
    ): Observable<DataProtocol.Collection<DbProtocol.HistoryEntry>> {
        return this.http
            .get(`${this.baseUrl}/api/history/role/employee/${personnelId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.HistoryEntry>(
                                DbProtocol.HistoryEntry
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getEmployeeRoleChangeHistoryForOffice(
        officeId: number
    ): Observable<DataProtocol.Collection<DbProtocol.HistoryEntry>> {
        return this.http
            .get(`${this.baseUrl}/api/history/role/office/${officeId}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.HistoryEntry>(
                                DbProtocol.HistoryEntry
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getCustomTimesheetHistory(
        cellIds: Array<number>
    ): Observable<DataProtocol.Collection<DbProtocol.HistoryEntry>> {
        return this.http
            .get(`${this.baseUrl}/api/history/timesheet/cells?cell_ids=${cellIds.join(',')}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.HistoryEntry>(
                                DbProtocol.HistoryEntry
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getMonthlyTimesheetHistoryForEmployee(
        year: number,
        month: number,
        personnelId: number
    ): Observable<DataProtocol.Collection<DbProtocol.HistoryEntry>> {
        return this.http
            .get(
                `${this.baseUrl}/api/history/timesheet/monthly/${year}/${month}/employee/${personnelId}`,
                { observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.HistoryEntry>(
                                DbProtocol.HistoryEntry
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getMonthlyTimesheetHistoryForProject(
        year: number,
        month: number,
        projectId: number
    ): Observable<DataProtocol.Collection<DbProtocol.HistoryEntry>> {
        return this.http
            .get(
                `${this.baseUrl}/api/history/timesheet/monthly/${year}/${month}/project/${projectId}`,
                { observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.HistoryEntry>(
                                DbProtocol.HistoryEntry
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getMonthlyTimesheetHistoryForOffice(
        year: number,
        month: number,
        officeId: number
    ): Observable<DataProtocol.Collection<DbProtocol.HistoryEntry>> {
        return this.http
            .get(
                `${this.baseUrl}/api/history/timesheet/monthly/${year}/${month}/office/${officeId}`,
                { observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.HistoryEntry>(
                                DbProtocol.HistoryEntry
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getMonthlyTimesheetHistoryForTeam(
        year: number,
        month: number,
        teamId: number
    ): Observable<DataProtocol.Collection<DbProtocol.HistoryEntry>> {
        return this.http
            .get(`${this.baseUrl}/api/history/timesheet/monthly/${year}/${month}/team/${teamId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.HistoryEntry>(
                                DbProtocol.HistoryEntry
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }
}
