// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DataProtocol from './data-protocol';
import * as DbProtocol from './db-protocol';
import * as WebProtocol from './web-protocol';
import * as CommonProtocol from './common-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesReportService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getVismaReportsForOffice(
        year: number,
        month: number,
        officeId: number
    ): Observable<DataProtocol.Collection<DbProtocol.VismaReport>> {
        return this.http
            .get(`${this.baseUrl}/api/reports/visma/${year}/${month}/office/${officeId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.VismaReport>(
                                DbProtocol.VismaReport
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getVismaReport(reportId: number): Observable<DbProtocol.VismaReport> {
        return this.http
            .get(`${this.baseUrl}/api/reports/visma/${reportId}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.VismaReport.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public createVismaReport(
        request: WebProtocol.CreateVismaReportRequest
    ): Observable<DbProtocol.VismaReport> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .post(`${this.baseUrl}/api/reports/visma`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.VismaReportError>(
                                        WebProtocol.VismaReportError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 201:
                        default:
                            return DbProtocol.VismaReport.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public updateVismaReport(
        request: WebProtocol.UpdateVismaReportRequest,
        reportId: number
    ): Observable<DbProtocol.VismaReport> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/reports/visma/${reportId}`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.VismaReportError>(
                                        WebProtocol.VismaReportError
                                    ).fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.VismaReport.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public downloadVismaReport(reportId: number): Observable<Igor.Json.JsonValue> {
        return this.http
            .get(`${this.baseUrl}/api/reports/visma/${reportId}/download`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return response.body as Igor.Json.JsonValue;
                    }
                })
            );
    }

    public deliverVismaReport(
        request: CommonProtocol.Empty,
        reportId: number
    ): Observable<DbProtocol.VismaReport> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .post(`${this.baseUrl}/api/reports/visma/${reportId}/deliver`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.VismaReportDeliveryError>(
                                        WebProtocol.VismaReportDeliveryError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.VismaReport.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public updateVismaReportDeliveryStatus(
        request: CommonProtocol.Empty,
        reportId: number
    ): Observable<DbProtocol.VismaReport> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .post(`${this.baseUrl}/api/reports/visma/${reportId}/status`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.VismaReportDeliveryError>(
                                        WebProtocol.VismaReportDeliveryError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.VismaReport.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getOmittedEmployeesForLastVismaReport(
        officeId: number
    ): Observable<WebProtocol.OmittedEmployees> {
        return this.http
            .get(`${this.baseUrl}/api/reports/visma/omitted/office/${officeId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return WebProtocol.OmittedEmployees.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }
}
