// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DataProtocol from './data-protocol';
import * as DbProtocol from './db-protocol';
import * as WebProtocol from './web-protocol';
import * as CommonProtocol from './common-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesRoleService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getRoles(): Observable<DataProtocol.Collection<DbProtocol.Role>> {
        return this.http.get(`${this.baseUrl}/api/roles`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.Role>(
                            DbProtocol.Role
                        ).fromJson(response.body as Igor.Json.JsonValue);
                }
            })
        );
    }

    public getRole(id: number): Observable<DbProtocol.Role> {
        return this.http.get(`${this.baseUrl}/api/roles/${id}`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                        case 404:
                            return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DbProtocol.Role.fromJson(response.body as Igor.Json.JsonValue);
                }
            })
        );
    }

    public createRole(request: WebProtocol.CreateRoleRequest): Observable<DbProtocol.Role> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .post(`${this.baseUrl}/api/roles`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.RoleError>(
                                        WebProtocol.RoleError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.Role.fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public updateRole(
        request: WebProtocol.UpdateRoleRequest,
        id: number
    ): Observable<DbProtocol.Role> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/roles/${id}`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.RoleError>(
                                        WebProtocol.RoleError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.Role.fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public deleteRole(id: number): Observable<DataProtocol.GenericResponse> {
        return this.http.delete(`${this.baseUrl}/api/roles/${id}`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                        case 404:
                            return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DataProtocol.GenericResponse.fromJson(
                            response.body as Igor.Json.JsonValue
                        );
                }
            })
        );
    }

    public enableRoleForOffice(
        request: CommonProtocol.Empty,
        id: number,
        officeId: number
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/roles/${id}/enable/${officeId}`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.RoleForOfficeError>(
                                        WebProtocol.RoleForOfficeError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public disableRoleForOffice(
        request: CommonProtocol.Empty,
        id: number,
        officeId: number
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/roles/${id}/disable/${officeId}`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.RoleForOfficeError>(
                                        WebProtocol.RoleForOfficeError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }
}
