// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as WebProtocol from './web-protocol';
import * as DataProtocol from './data-protocol';
import * as CommonProtocol from './common-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesTaskService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public syncBamboo(
        request: WebProtocol.SyncBambooTaskRequest,
        year: number,
        month: number
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(
                `${this.baseUrl}/api/tasks/sync_bamboo/monthly/${year}/${month}`,
                request.toJson(),
                { headers: headers, observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public syncLdap(request: CommonProtocol.Empty): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/tasks/sync_ldap`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }
}
