// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DataProtocol from './data-protocol';
import * as DbProtocol from './db-protocol';
import * as WebProtocol from './web-protocol';
import * as CommonProtocol from './common-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesTeamService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getTeams(): Observable<DataProtocol.Collection<DbProtocol.Team>> {
        return this.http.get(`${this.baseUrl}/api/teams`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.Team>(
                            DbProtocol.Team
                        ).fromJson(response.body as Igor.Json.JsonValue);
                }
            })
        );
    }

    public getTeam(id: number): Observable<DbProtocol.Team> {
        return this.http.get(`${this.baseUrl}/api/teams/${id}`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                        case 404:
                            return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DbProtocol.Team.fromJson(response.body as Igor.Json.JsonValue);
                }
            })
        );
    }

    public createTeam(request: WebProtocol.CreateTeamRequest): Observable<DbProtocol.Team> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .post(`${this.baseUrl}/api/teams`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.TeamError>(
                                        WebProtocol.TeamError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.Team.fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public updateTeam(
        request: WebProtocol.UpdateTeamRequest,
        id: number
    ): Observable<DbProtocol.Team> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/teams/${id}`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.TeamError>(
                                        WebProtocol.TeamError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.Team.fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public deleteTeam(id: number): Observable<DataProtocol.GenericResponse> {
        return this.http.delete(`${this.baseUrl}/api/teams/${id}`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                        case 404:
                            return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DataProtocol.GenericResponse.fromJson(
                            response.body as Igor.Json.JsonValue
                        );
                }
            })
        );
    }

    public addTeamMember(
        request: CommonProtocol.Empty,
        teamId: number,
        personnelId: number
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/teams/${teamId}/members/${personnelId}`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.TeamMemberError>(
                                        WebProtocol.TeamMemberError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public removeTeamMember(
        teamId: number,
        personnelId: number
    ): Observable<DataProtocol.GenericResponse> {
        return this.http
            .delete(`${this.baseUrl}/api/teams/${teamId}/members/${personnelId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.TeamMemberError>(
                                        WebProtocol.TeamMemberError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getTeamManagers(
        teamId: number
    ): Observable<DataProtocol.Collection<DbProtocol.PersonnelAccount>> {
        return this.http
            .get(`${this.baseUrl}/api/teams/${teamId}/managers`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.PersonnelAccount>(
                                DbProtocol.PersonnelAccount
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public isCurrentUserTeamManager(teamId: number): Observable<DataProtocol.GenericResponse> {
        return this.http
            .get(`${this.baseUrl}/api/teams/${teamId}/manager`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public isTeamManager(
        teamId: number,
        personnelId: number
    ): Observable<DataProtocol.GenericResponse> {
        return this.http
            .get(`${this.baseUrl}/api/teams/${teamId}/members/${personnelId}/manager`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public setTeamManager(
        request: CommonProtocol.Empty,
        teamId: number,
        personnelId: number
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(
                `${this.baseUrl}/api/teams/${teamId}/members/${personnelId}/manager`,
                request.toJson(),
                { headers: headers, observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.TeamManagerError>(
                                        WebProtocol.TeamManagerError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public unsetTeamManager(
        teamId: number,
        personnelId: number
    ): Observable<DataProtocol.GenericResponse> {
        return this.http
            .delete(`${this.baseUrl}/api/teams/${teamId}/members/${personnelId}/manager`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.TeamManagerError>(
                                        WebProtocol.TeamManagerError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }
}
