// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DbProtocol from './db-protocol';
import * as DataProtocol from './data-protocol';
import * as WebProtocol from './web-protocol';
import * as CommonProtocol from './common-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesTimesheetService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getTimesheetCell(cellId: number): Observable<DbProtocol.TimesheetCell> {
        return this.http
            .get(`${this.baseUrl}/api/timesheet/cell/${cellId}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.TimesheetCell.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public allocateTimesheetCellBulk(
        request: WebProtocol.BulkTimesheetAllocate
    ): Observable<Array<DbProtocol.TimesheetCell>> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/timesheet/bulk/allocate`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.TimesheetCellAllocError>(
                                        WebProtocol.TimesheetCellAllocError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return Igor.Json.List(DbProtocol.TimesheetCell).fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public resetTimesheetCellBulk(
        request: WebProtocol.BulkTimesheetAction
    ): Observable<Array<DbProtocol.TimesheetCell>> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/timesheet/bulk/reset`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return Igor.Json.List(DbProtocol.TimesheetCell).fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public setTimesheetCellOffBulk(
        request: WebProtocol.BulkTimesheetTimeOff
    ): Observable<Array<DbProtocol.TimesheetCell>> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/timesheet/bulk/off`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.TimesheetCellOffError>(
                                        WebProtocol.TimesheetCellOffError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return Igor.Json.List(DbProtocol.TimesheetCell).fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public protectTimesheetCellBulk(
        request: WebProtocol.BulkTimesheetProtect
    ): Observable<Array<DbProtocol.TimesheetCell>> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/timesheet/bulk/protect`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return Igor.Json.List(DbProtocol.TimesheetCell).fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public unprotectTimesheetCellBulk(
        request: WebProtocol.BulkTimesheetProtect
    ): Observable<Array<DbProtocol.TimesheetCell>> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/timesheet/bulk/unprotect`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return Igor.Json.List(DbProtocol.TimesheetCell).fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public regenerateTimesheetCells(
        request: CommonProtocol.Empty,
        year: number,
        month: number
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(
                `${this.baseUrl}/api/timesheet/monthly/${year}/${month}/regenerate`,
                request.toJson(),
                { headers: headers, observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public protectTimesheetMonthForEmployee(
        request: CommonProtocol.Empty,
        year: number,
        month: number,
        personnelId: number
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(
                `${this.baseUrl}/api/timesheet/monthly/${year}/${month}/employee/${personnelId}/protect`,
                request.toJson(),
                { headers: headers, observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public unprotectTimesheetMonthForEmployee(
        year: number,
        month: number,
        personnelId: number
    ): Observable<DataProtocol.GenericResponse> {
        return this.http
            .delete(
                `${this.baseUrl}/api/timesheet/monthly/${year}/${month}/employee/${personnelId}/protect`,
                { observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getMonthlyTimesheetForEmployee(
        year: number,
        month: number,
        personnelId: number
    ): Observable<WebProtocol.MonthlyEmployeeTimesheet> {
        return this.http
            .get(`${this.baseUrl}/api/timesheet/monthly/${year}/${month}/employee/${personnelId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return WebProtocol.MonthlyEmployeeTimesheet.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getMonthlyTimesheetForProject(
        year: number,
        month: number,
        projectId: number
    ): Observable<DataProtocol.Collection<WebProtocol.MonthlyEmployeeTimesheet>> {
        return this.http
            .get(`${this.baseUrl}/api/timesheet/monthly/${year}/${month}/project/${projectId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<WebProtocol.MonthlyEmployeeTimesheet>(
                                WebProtocol.MonthlyEmployeeTimesheet
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getMonthlyTimesheetForOffice(
        year: number,
        month: number,
        officeId: number
    ): Observable<DataProtocol.Collection<WebProtocol.MonthlyEmployeeTimesheet>> {
        return this.http
            .get(`${this.baseUrl}/api/timesheet/monthly/${year}/${month}/office/${officeId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<WebProtocol.MonthlyEmployeeTimesheet>(
                                WebProtocol.MonthlyEmployeeTimesheet
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getMonthlyTimesheetForTeam(
        year: number,
        month: number,
        teamId: number
    ): Observable<DataProtocol.Collection<WebProtocol.MonthlyEmployeeTimesheet>> {
        return this.http
            .get(`${this.baseUrl}/api/timesheet/monthly/${year}/${month}/team/${teamId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<WebProtocol.MonthlyEmployeeTimesheet>(
                                WebProtocol.MonthlyEmployeeTimesheet
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getMonthlyTimesheetForEveryone(
        year: number,
        month: number
    ): Observable<DataProtocol.Collection<WebProtocol.MonthlyEmployeeTimesheet>> {
        return this.http
            .get(`${this.baseUrl}/api/timesheet/monthly/${year}/${month}/everyone`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<WebProtocol.MonthlyEmployeeTimesheet>(
                                WebProtocol.MonthlyEmployeeTimesheet
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }
}
