// Author: Igor compiler
// Compiler version: igorc 2.1.2
// DO NOT EDIT THIS FILE - it is machine generated

import * as Igor from './igor';

export class VismaSummaryEntry {
    projectId!: string;
    projectTask!: string;
    invoiceable!: boolean;
    mon?: number | null = null;
    tue?: number | null = null;
    wed?: number | null = null;
    thu?: number | null = null;
    fri?: number | null = null;
    sat?: number | null = null;
    sun?: number | null = null;

    static fromJson(json: Igor.Json.JsonValue): VismaSummaryEntry {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new VismaSummaryEntry();
        obj.projectId = jsonObject['projectId'] as string;
        obj.projectTask = jsonObject['projectTask'] as string;
        obj.invoiceable = jsonObject['invoiceable'] as boolean;
        obj.mon =
            'mon' in jsonObject && jsonObject['mon'] != null ? (jsonObject['mon'] as number) : null;
        obj.tue =
            'tue' in jsonObject && jsonObject['tue'] != null ? (jsonObject['tue'] as number) : null;
        obj.wed =
            'wed' in jsonObject && jsonObject['wed'] != null ? (jsonObject['wed'] as number) : null;
        obj.thu =
            'thu' in jsonObject && jsonObject['thu'] != null ? (jsonObject['thu'] as number) : null;
        obj.fri =
            'fri' in jsonObject && jsonObject['fri'] != null ? (jsonObject['fri'] as number) : null;
        obj.sat =
            'sat' in jsonObject && jsonObject['sat'] != null ? (jsonObject['sat'] as number) : null;
        obj.sun =
            'sun' in jsonObject && jsonObject['sun'] != null ? (jsonObject['sun'] as number) : null;
        return obj;
    }

    static toJson(value: VismaSummaryEntry): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['projectId'] = value.projectId;
        result['projectTask'] = value.projectTask;
        result['invoiceable'] = value.invoiceable;
        if (value.mon != null) result['mon'] = value.mon;
        if (value.tue != null) result['tue'] = value.tue;
        if (value.wed != null) result['wed'] = value.wed;
        if (value.thu != null) result['thu'] = value.thu;
        if (value.fri != null) result['fri'] = value.fri;
        if (value.sat != null) result['sat'] = value.sat;
        if (value.sun != null) result['sun'] = value.sun;
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return VismaSummaryEntry.toJson(this);
    }
}

export class VismaWeekEntry {
    week!: string;
    internalRefNr!: string;
    summary!: Array<VismaSummaryEntry>;

    static fromJson(json: Igor.Json.JsonValue): VismaWeekEntry {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new VismaWeekEntry();
        obj.week = jsonObject['week'] as string;
        obj.internalRefNr = jsonObject['internalRefNr'] as string;
        obj.summary = Igor.Json.List(VismaSummaryEntry).fromJson(jsonObject['summary']);
        return obj;
    }

    static toJson(value: VismaWeekEntry): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['week'] = value.week;
        result['internalRefNr'] = value.internalRefNr;
        result['summary'] = Igor.Json.List(VismaSummaryEntry).toJson(value.summary);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return VismaWeekEntry.toJson(this);
    }
}

export class VismaEmployeeEntry {
    employeeId!: string;
    dateFrom!: string;
    dateTo!: string;
    weeks!: Array<VismaWeekEntry>;

    static fromJson(json: Igor.Json.JsonValue): VismaEmployeeEntry {
        const jsonObject = json as Igor.Json.JsonObject;
        const obj = new VismaEmployeeEntry();
        obj.employeeId = jsonObject['employeeId'] as string;
        obj.dateFrom = jsonObject['dateFrom'] as string;
        obj.dateTo = jsonObject['dateTo'] as string;
        obj.weeks = Igor.Json.List(VismaWeekEntry).fromJson(jsonObject['weeks']);
        return obj;
    }

    static toJson(value: VismaEmployeeEntry): Igor.Json.JsonValue {
        const result: Igor.Json.JsonObject = {};
        result['employeeId'] = value.employeeId;
        result['dateFrom'] = value.dateFrom;
        result['dateTo'] = value.dateTo;
        result['weeks'] = Igor.Json.List(VismaWeekEntry).toJson(value.weeks);
        return result;
    }

    toJson(): Igor.Json.JsonValue {
        return VismaEmployeeEntry.toJson(this);
    }
}
