// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DataProtocol from './data-protocol';
import * as DbProtocol from './db-protocol';
import * as WebProtocol from './web-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesOfficeService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getOffices(): Observable<DataProtocol.Collection<DbProtocol.Office>> {
        return this.http.get(`${this.baseUrl}/api/offices`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.Office>(
                            DbProtocol.Office
                        ).fromJson(response.body as Igor.Json.JsonValue);
                }
            })
        );
    }

    public getOffice(id: number): Observable<DbProtocol.Office> {
        return this.http.get(`${this.baseUrl}/api/offices/${id}`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                        case 404:
                            return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DbProtocol.Office.fromJson(response.body as Igor.Json.JsonValue);
                }
            })
        );
    }

    public createOffice(request: WebProtocol.CreateOfficeRequest): Observable<DbProtocol.Office> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .post(`${this.baseUrl}/api/offices`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.OfficeManagementError>(
                                        WebProtocol.OfficeManagementError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.Office.fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public updateOffice(
        request: WebProtocol.UpdateOfficeRequest,
        id: number
    ): Observable<DbProtocol.Office> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/offices/${id}`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.OfficeManagementError>(
                                        WebProtocol.OfficeManagementError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.Office.fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public deleteOffice(id: number): Observable<DataProtocol.GenericResponse> {
        return this.http.delete(`${this.baseUrl}/api/offices/${id}`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                        case 404:
                            return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DataProtocol.GenericResponse.fromJson(
                            response.body as Igor.Json.JsonValue
                        );
                }
            })
        );
    }
}
