// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as WebProtocol from './web-protocol';
import * as DataProtocol from './data-protocol';
import * as CommonProtocol from './common-protocol';
import * as DbProtocol from './db-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesAuthService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getPersonnelStatus(): Observable<WebProtocol.PersonnelStatusResponse> {
        return this.http
            .get(`${this.baseUrl}/api/auth/personnel/status`, { observe: 'response' })
            .pipe(
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return WebProtocol.PersonnelStatusResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public loginPersonnel(
        request: WebProtocol.PersonnelLoginRequest
    ): Observable<WebProtocol.PersonnelLoginResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .post(`${this.baseUrl}/api/auth/personnel/login`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.PersonnelLoginError>(
                                        WebProtocol.PersonnelLoginError
                                    ).fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return WebProtocol.PersonnelLoginResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public logoutPersonnel(
        request: CommonProtocol.Empty
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/auth/personnel/logout`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getMyPersonnelProfile(): Observable<DbProtocol.PersonnelAccount> {
        return this.http
            .get(`${this.baseUrl}/api/auth/personnel/profile`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getMyRolesForProject(projectId: number): Observable<DbProtocol.PersonnelAccountRole> {
        return this.http
            .get(`${this.baseUrl}/api/auth/personnel/roles/${projectId}/me`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccountRole.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }
}
