// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DbProtocol from './db-protocol';
import * as DataProtocol from './data-protocol';
import * as WebProtocol from './web-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesAdminService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getPersonnelAccount(id: number): Observable<DbProtocol.PersonnelAccount> {
        return this.http
            .get(`${this.baseUrl}/api/admin/personnel/${id}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public updatePersonnelAccount(
        request: WebProtocol.UpdatePersonnelAccountRequest,
        id: number
    ): Observable<DbProtocol.PersonnelAccount> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/admin/personnel/${id}`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.UpdatePersonnelAccountError>(
                                        WebProtocol.UpdatePersonnelAccountError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getPersonnelAccountByUsername(
        username: string
    ): Observable<DbProtocol.PersonnelAccount> {
        return this.http
            .get(`${this.baseUrl}/api/admin/personnel/username/${username}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getPersonnelAccounts(
        needle: string | null = null,
        orderBy: WebProtocol.PersonnelAccountOrderBy,
        orderDir: DataProtocol.OrderDirection,
        offset: number,
        limit: number
    ): Observable<DataProtocol.CollectionSlice<DbProtocol.PersonnelAccount>> {
        const queryParams: Array<string> = [];
        if (needle != null) queryParams.push(`needle=${needle}`);
        queryParams.push(`order_by=${WebProtocol.PersonnelAccountOrderBy.toJson(orderBy)}`);
        queryParams.push(`order_dir=${DataProtocol.OrderDirection.toJson(orderDir)}`);
        queryParams.push(`offset=${offset}`);
        queryParams.push(`limit=${limit}`);
        const queryString = queryParams.length > 0 ? `?${queryParams.join('&')}` : '';

        return this.http
            .get(`${this.baseUrl}/api/admin/personnels${queryString}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.CollectionSlice.instanceJsonSerializer<DbProtocol.PersonnelAccount>(
                                DbProtocol.PersonnelAccount
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getPersonnelAccountRoles(
        id: number,
        needle: string | null = null,
        orderBy: WebProtocol.PersonnelAccountRoleOrderBy,
        orderDir: DataProtocol.OrderDirection,
        offset: number,
        limit: number
    ): Observable<DataProtocol.CollectionSlice<DbProtocol.PersonnelAccountRole>> {
        const queryParams: Array<string> = [];
        if (needle != null) queryParams.push(`needle=${needle}`);
        queryParams.push(`order_by=${WebProtocol.PersonnelAccountRoleOrderBy.toJson(orderBy)}`);
        queryParams.push(`order_dir=${DataProtocol.OrderDirection.toJson(orderDir)}`);
        queryParams.push(`offset=${offset}`);
        queryParams.push(`limit=${limit}`);
        const queryString = queryParams.length > 0 ? `?${queryParams.join('&')}` : '';

        return this.http
            .get(`${this.baseUrl}/api/admin/personnel/${id}/roles${queryString}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.CollectionSlice.instanceJsonSerializer<DbProtocol.PersonnelAccountRole>(
                                DbProtocol.PersonnelAccountRole
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getPersonnelAccountRolesForProject(
        projectId: number,
        needle: string | null = null,
        orderBy: WebProtocol.PersonnelAccountRoleOrderBy,
        orderDir: DataProtocol.OrderDirection,
        offset: number,
        limit: number
    ): Observable<DataProtocol.CollectionSlice<DbProtocol.PersonnelAccountRole>> {
        const queryParams: Array<string> = [];
        if (needle != null) queryParams.push(`needle=${needle}`);
        queryParams.push(`order_by=${WebProtocol.PersonnelAccountRoleOrderBy.toJson(orderBy)}`);
        queryParams.push(`order_dir=${DataProtocol.OrderDirection.toJson(orderDir)}`);
        queryParams.push(`offset=${offset}`);
        queryParams.push(`limit=${limit}`);
        const queryString = queryParams.length > 0 ? `?${queryParams.join('&')}` : '';

        return this.http
            .get(`${this.baseUrl}/api/admin/personnel/project/${projectId}/roles${queryString}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.CollectionSlice.instanceJsonSerializer<DbProtocol.PersonnelAccountRole>(
                                DbProtocol.PersonnelAccountRole
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getPersonnelAccountRole(
        id: number,
        projectId: number
    ): Observable<DbProtocol.PersonnelAccountRole> {
        return this.http
            .get(`${this.baseUrl}/api/admin/personnel/${id}/roles/${projectId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccountRole.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public setPersonnelAccountRole(
        request: WebProtocol.AccessRoleUpdateRequest,
        id: number,
        projectId: number
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/admin/personnel/${id}/roles/${projectId}`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public resetPersonnelAccountRole(
        id: number,
        projectId: number
    ): Observable<DataProtocol.GenericResponse> {
        return this.http
            .delete(`${this.baseUrl}/api/admin/personnel/${id}/roles/${projectId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getPersonnelGroup(id: number): Observable<DbProtocol.PersonnelGroup> {
        return this.http
            .get(`${this.baseUrl}/api/admin/personnel-groups/${id}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelGroup.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getPersonnelGroupByName(name: string): Observable<DbProtocol.PersonnelGroup> {
        return this.http
            .get(`${this.baseUrl}/api/admin/personnel-groups/name/${name}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelGroup.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getPersonnelGroups(
        needle: string | null = null,
        orderBy: WebProtocol.PersonnelGroupOrderBy,
        orderDir: DataProtocol.OrderDirection,
        offset: number,
        limit: number
    ): Observable<DataProtocol.CollectionSlice<DbProtocol.PersonnelGroup>> {
        const queryParams: Array<string> = [];
        if (needle != null) queryParams.push(`needle=${needle}`);
        queryParams.push(`order_by=${WebProtocol.PersonnelGroupOrderBy.toJson(orderBy)}`);
        queryParams.push(`order_dir=${DataProtocol.OrderDirection.toJson(orderDir)}`);
        queryParams.push(`offset=${offset}`);
        queryParams.push(`limit=${limit}`);
        const queryString = queryParams.length > 0 ? `?${queryParams.join('&')}` : '';

        return this.http
            .get(`${this.baseUrl}/api/admin/personnel-groups${queryString}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.CollectionSlice.instanceJsonSerializer<DbProtocol.PersonnelGroup>(
                                DbProtocol.PersonnelGroup
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getPersonnelGroupRoles(
        id: number,
        needle: string | null = null,
        orderBy: WebProtocol.PersonnelGroupRoleOrderBy,
        orderDir: DataProtocol.OrderDirection,
        offset: number,
        limit: number
    ): Observable<DataProtocol.CollectionSlice<DbProtocol.PersonnelGroupRole>> {
        const queryParams: Array<string> = [];
        if (needle != null) queryParams.push(`needle=${needle}`);
        queryParams.push(`order_by=${WebProtocol.PersonnelGroupRoleOrderBy.toJson(orderBy)}`);
        queryParams.push(`order_dir=${DataProtocol.OrderDirection.toJson(orderDir)}`);
        queryParams.push(`offset=${offset}`);
        queryParams.push(`limit=${limit}`);
        const queryString = queryParams.length > 0 ? `?${queryParams.join('&')}` : '';

        return this.http
            .get(`${this.baseUrl}/api/admin/personnel-groups/${id}/roles${queryString}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.CollectionSlice.instanceJsonSerializer<DbProtocol.PersonnelGroupRole>(
                                DbProtocol.PersonnelGroupRole
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getPersonnelGroupRolesForProject(
        projectId: number,
        needle: string | null = null,
        orderBy: WebProtocol.PersonnelGroupRoleOrderBy,
        orderDir: DataProtocol.OrderDirection,
        offset: number,
        limit: number
    ): Observable<DataProtocol.CollectionSlice<DbProtocol.PersonnelGroupRole>> {
        const queryParams: Array<string> = [];
        if (needle != null) queryParams.push(`needle=${needle}`);
        queryParams.push(`order_by=${WebProtocol.PersonnelGroupRoleOrderBy.toJson(orderBy)}`);
        queryParams.push(`order_dir=${DataProtocol.OrderDirection.toJson(orderDir)}`);
        queryParams.push(`offset=${offset}`);
        queryParams.push(`limit=${limit}`);
        const queryString = queryParams.length > 0 ? `?${queryParams.join('&')}` : '';

        return this.http
            .get(
                `${this.baseUrl}/api/admin/personnel-groups/project/${projectId}/roles${queryString}`,
                { observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.CollectionSlice.instanceJsonSerializer<DbProtocol.PersonnelGroupRole>(
                                DbProtocol.PersonnelGroupRole
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getPersonnelGroupRole(
        id: number,
        projectId: number
    ): Observable<DbProtocol.PersonnelGroupRole> {
        return this.http
            .get(`${this.baseUrl}/api/admin/personnel-groups/${id}/roles/${projectId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelGroupRole.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public setPersonnelGroupRole(
        request: WebProtocol.AccessRoleUpdateRequest,
        id: number,
        projectId: number
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(
                `${this.baseUrl}/api/admin/personnel-groups/${id}/roles/${projectId}`,
                request.toJson(),
                { headers: headers, observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public resetPersonnelGroupRole(
        id: number,
        projectId: number
    ): Observable<DataProtocol.GenericResponse> {
        return this.http
            .delete(`${this.baseUrl}/api/admin/personnel-groups/${id}/roles/${projectId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getSettings(): Observable<WebProtocol.Settings> {
        return this.http.get(`${this.baseUrl}/api/admin/settings`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return WebProtocol.Settings.fromJson(response.body as Igor.Json.JsonValue);
                }
            })
        );
    }

    public updateSettings(
        request: WebProtocol.SettingsUpdateRequest
    ): Observable<DataProtocol.GenericResponse> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/admin/settings`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.GenericResponse.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }
}
