// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DataProtocol from './data-protocol';
import * as DbProtocol from './db-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesDirectoryService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getCountries(): Observable<DataProtocol.Collection<DbProtocol.Country>> {
        return this.http
            .get(`${this.baseUrl}/api/directory/countries`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.Country>(
                                DbProtocol.Country
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getCountry(id: number): Observable<DbProtocol.Country> {
        return this.http
            .get(`${this.baseUrl}/api/directory/countries/${id}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.Country.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }
}
