// Author: Igor compiler
// Compiler version: igorc 2.1.4
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DbProtocol from './db-protocol';
import * as DataProtocol from './data-protocol';
import * as WebProtocol from './web-protocol';
import * as CommonProtocol from './common-protocol';

@Injectable({
    providedIn: 'root'
})
export class HermesEmployeeService {
    public baseUrl = '';

    constructor(private http: HttpClient) {}

    public getEmployee(id: number): Observable<DbProtocol.PersonnelAccount> {
        return this.http.get(`${this.baseUrl}/api/employees/${id}`, { observe: 'response' }).pipe(
            catchError((response) => {
                if (response instanceof HttpErrorResponse) {
                    switch (response.status) {
                        case 403:
                            return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                        case 404:
                            return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                    }
                }
                return throwError(response);
            }),
            map((response) => {
                switch (response.status) {
                    case 200:
                    default:
                        return DbProtocol.PersonnelAccount.fromJson(
                            response.body as Igor.Json.JsonValue
                        );
                }
            })
        );
    }

    public getEmployeeByUsername(username: string): Observable<DbProtocol.PersonnelAccount> {
        return this.http
            .get(`${this.baseUrl}/api/employees/username/${username}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public getEmployees(
        needle: string | null = null,
        orderBy: WebProtocol.PersonnelAccountOrderBy,
        orderDir: DataProtocol.OrderDirection,
        offset: number,
        limit: number
    ): Observable<DataProtocol.CollectionSlice<DbProtocol.PersonnelAccount>> {
        const queryParams: Array<string> = [];
        if (needle != null) queryParams.push(`needle=${needle}`);
        queryParams.push(`order_by=${WebProtocol.PersonnelAccountOrderBy.toJson(orderBy)}`);
        queryParams.push(`order_dir=${DataProtocol.OrderDirection.toJson(orderDir)}`);
        queryParams.push(`offset=${offset}`);
        queryParams.push(`limit=${limit}`);
        const queryString = queryParams.length > 0 ? `?${queryParams.join('&')}` : '';

        return this.http
            .get(`${this.baseUrl}/api/employees${queryString}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.CollectionSlice.instanceJsonSerializer<DbProtocol.PersonnelAccount>(
                                DbProtocol.PersonnelAccount
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getEmployeesByOffice(
        officeId: number
    ): Observable<DataProtocol.Collection<DbProtocol.PersonnelAccount>> {
        return this.http
            .get(`${this.baseUrl}/api/employees/office/${officeId}`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.PersonnelAccount>(
                                DbProtocol.PersonnelAccount
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public getEmployeesByProject(
        projectId: number,
        since: Date | null = null,
        till: Date | null = null
    ): Observable<DataProtocol.Collection<DbProtocol.PersonnelAccount>> {
        const queryParams: Array<string> = [];
        if (since != null)
            queryParams.push(
                `since=${since != null ? Igor.Json.DateSerializer.toJson(since) : null}`
            );
        if (till != null)
            queryParams.push(`till=${till != null ? Igor.Json.DateSerializer.toJson(till) : null}`);
        const queryString = queryParams.length > 0 ? `?${queryParams.join('&')}` : '';

        return this.http
            .get(`${this.baseUrl}/api/employees/project/${projectId}${queryString}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DataProtocol.Collection.instanceJsonSerializer<DbProtocol.PersonnelAccount>(
                                DbProtocol.PersonnelAccount
                            ).fromJson(response.body as Igor.Json.JsonValue);
                    }
                })
            );
    }

    public allocateEmployee(
        request: WebProtocol.EmployeeAlloc,
        id: number
    ): Observable<DbProtocol.PersonnelAccount> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(`${this.baseUrl}/api/employees/${id}/alloc`, request.toJson(), {
                headers: headers,
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400:
                                return throwError(
                                    DataProtocol.BadRequestError.instanceJsonSerializer<WebProtocol.EmployeeAllocError>(
                                        WebProtocol.EmployeeAllocError
                                    ).fromJson(response.error)
                                );
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public deallocateEmployee(id: number): Observable<DbProtocol.PersonnelAccount> {
        return this.http
            .delete(`${this.baseUrl}/api/employees/${id}/alloc`, { observe: 'response' })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public addEmployeeHighlight(
        request: CommonProtocol.Empty,
        personnelId: number,
        projectId: number,
        highlightId: number
    ): Observable<DbProtocol.PersonnelAccount> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(
                `${this.baseUrl}/api/employees/${personnelId}/project/${projectId}/highlight/${highlightId}`,
                request.toJson(),
                { headers: headers, observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public removeEmployeeHighlight(
        personnelId: number,
        projectId: number,
        highlightId: number
    ): Observable<DbProtocol.PersonnelAccount> {
        return this.http
            .delete(
                `${this.baseUrl}/api/employees/${personnelId}/project/${projectId}/highlight/${highlightId}`,
                { observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public linkEmployeeToProject(
        request: CommonProtocol.Empty,
        personnelId: number,
        projectId: number
    ): Observable<DbProtocol.PersonnelAccount> {
        const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

        return this.http
            .put(
                `${this.baseUrl}/api/employees/${personnelId}/project/${projectId}`,
                request.toJson(),
                { headers: headers, observe: 'response' }
            )
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }

    public unlinkEmployeeFromProject(
        personnelId: number,
        projectId: number
    ): Observable<DbProtocol.PersonnelAccount> {
        return this.http
            .delete(`${this.baseUrl}/api/employees/${personnelId}/project/${projectId}`, {
                observe: 'response'
            })
            .pipe(
                catchError((response) => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403:
                                return throwError(
                                    DataProtocol.ForbiddenError.fromJson(response.error)
                                );
                            case 404:
                                return throwError(
                                    DataProtocol.NotFoundError.fromJson(response.error)
                                );
                        }
                    }
                    return throwError(response);
                }),
                map((response) => {
                    switch (response.status) {
                        case 200:
                        default:
                            return DbProtocol.PersonnelAccount.fromJson(
                                response.body as Igor.Json.JsonValue
                            );
                    }
                })
            );
    }
}
